### PR TITLE
Improve typography

### PR DESCRIPTION
**Pull request by timparenti**
This is my huge typography branch.  Lots of goodies in here that I've been working on throughout the week.

I will still have another "nits" branch soon on typos, wordings, and the like, but I wanted to get this out before it becomes any more painful to rebase.

### CODE REVIEW

**Comment by timparenti** [comment]
I haven't checked to see whether this will cause conflicts with #38; it seems somewhat likely, so feel free to pull that in first, and I'll rebase if necessary.

**Comment by laboon** [comment]
Yeah looks like it's going to need a rebase.

**Comment by timparenti** [comment]
Yeah, one problem with typography fixes such as these is that _they touch almost everything._

If you're still going strong for the morning, keep going, but maybe point out here when you break for lunch so I can crank out the rebase before more changes crop up?

**Comment by laboon** [comment]
OK, breaking for lunch if you want to rebase.  I won't touch master again until I hear from you.

Thanks!

**Comment by timparenti** [comment]
Okay!  Should be good now.

For some of the more global stylistic changes, `git rebase` wouldn't have caught things added more recently, but I at least fixed up where there were conflicts.  I'll make another pass through now and add a commit if necessary.

**Comment by timparenti** [comment]
Only found one minor thing, which I rebased in.  Ready now.

**Comment by laboon** [comment]
Looks good, merging.  Thanks!

**Pull request merged**
