### PR TITLE
Inline links instead of showing the URL

### PR DESCRIPTION
**Pull request by shepmaster**

### CODE REVIEW

**Comment by timparenti** [comment]
++, this was on my list of things to ask about.

I can see this going both ways, though. In particular, if this is to be printed someday, it would be helpful to have sufficiently descriptive (but perhaps non-URL) pointers to the content in the text itself. There's probably a happy medium to be found here.

**Comment by laboon** [comment]
I plan on having this printed.  Having the URL as a footnote would be ideal, but I don't think I can do that in Markdown.  And I don't want to rewrite it from scratch.

**Comment by timparenti** [comment]
IIRC, some flavors of Markdown allow for footnotes; the question is whether `pandoc` will do the right thing with them. Let me look into this today.

**Comment by timparenti** [comment]
I just issued #115 which uses footnotes instead.

**Comment by laboon** [comment]
#115 looks nice!  overrrides this one.

Thanks @timparenti

**Pull request closed without merging**
